### ISSUE TITLE
Color Palette has been updated

### ISSUE THREAD

**Issue by skbolton** [embark-theme/Konsole#2]
@Reiddragon would you be able to help me out with this? I am not a Konsole user. 

The following colors have changed

- light cyan
- dark green
- dark blue
- dark purple

The new codes can be seen on the [homepage](https://embark-theme.github.io/) or in the [kitty theme](https://github.com/embark-theme/kitty).

If I don't hear back from you I will give it a go. I was just trying to avoid
installing Konsole and figuring it all out.

**Comment by Reiddragon** [comment]
opened https://github.com/embark-theme/Konsole/pull/3 with the updated colours, hope that does it
